"use client";

import { memo, type CSSProperties, type ReactNode } from "react";
import { motion } from "framer-motion";
import { Activity, CheckCircle2, GitBranch, Network, Radar, ShieldAlert, Zap } from "lucide-react";
import type { ConsensusResult, GovernanceEvent, GovernanceMetrics, ProposalHistoryItem, RiskAnalysis, SimulationValidator } from "@/lib/api";

export function LoadingSkeleton({ rows = 3 }: { rows?: number }) {
  return <div className="space-y-3" aria-label="Loading intelligence data">{Array.from({ length: rows }).map((_, index) => <div key={index} className="h-20 animate-pulse rounded-2xl border border-white/10 bg-white/[0.04]" />)}</div>;
}

export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) {
  return <div className="rounded-3xl border border-dashed border-violet-200 bg-white/70 p-8 text-center"><Radar className="mx-auto text-violet-500" size={34} /><h3 className="mt-4 text-lg font-semibold text-slate-950">{title}</h3><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-slate-500">{description}</p>{action ? <div className="mt-5">{action}</div> : null}</div>;
}

export const ConsensusRing = memo(function ConsensusRing({ score = 0, label = "weighted consensus" }: { score?: number; label?: string }) {
  const boundedScore = Math.max(0, Math.min(100, Math.round(score)));
  return <div className="flex items-center gap-5 rounded-3xl border border-violet-200/70 bg-white/80 p-5"><motion.div className="cs-ring flex h-32 w-32 shrink-0 items-center justify-center rounded-full p-2" style={{ "--score": `${boundedScore}%` } as CSSProperties} initial={{ rotate: -40, opacity: 0 }} animate={{ rotate: 0, opacity: 1 }}><div className="flex h-full w-full items-center justify-center rounded-full bg-white text-center shadow-inner"><div><p className="text-3xl font-black text-slate-950">{boundedScore}%</p><p className="text-[10px] uppercase tracking-[0.18em] text-violet-600">live</p></div></div></motion.div><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-violet-600">{label}</p><p className="mt-2 text-sm leading-6 text-slate-600">Animated consensus confidence from the AI Validator Swarm, weighted by specialization and memory state.</p></div></div>;
});

export const SwarmVisualization = memo(function SwarmVisualization({ validators }: { validators: SimulationValidator[] }) {
  const nodes = validators;
  const fractured = nodes.some((node) => node.disagrees);
  return <div className="relative min-h-[360px] overflow-hidden rounded-3xl border border-violet-200 bg-white/80 p-6"><div className="absolute inset-0 cs-grid opacity-35" />{nodes.length ? <svg className="absolute inset-0 h-full w-full" aria-hidden="true">{nodes.map((node, index) => { const angle = (index / nodes.length) * Math.PI * 2; const x = 50 + Math.cos(angle) * 34; const y = 50 + Math.sin(angle) * 34; return <motion.line key={node.validator} x1="50%" y1="50%" x2={`${x}%`} y2={`${y}%`} stroke={node.disagrees ? "rgba(239,68,68,0.72)" : "rgba(124,58,237,0.34)"} strokeWidth={node.disagrees ? "2" : "1"} strokeDasharray={node.disagrees ? "2 6" : "5 7"} animate={{ opacity: node.disagrees ? [0.25, 1, 0.25] : [0.28, 0.75, 0.28] }} transition={{ duration: node.disagrees ? 1.2 : 2.4, repeat: Infinity, delay: index * 0.2 }} />; })}</svg> : null}<motion.div className={`absolute left-1/2 top-1/2 h-28 w-28 -translate-x-1/2 -translate-y-1/2 rounded-full border ${fractured ? "border-rose-300/70 bg-rose-500/10 shadow-[0_0_50px_rgba(239,68,68,0.22)]" : "border-violet-300/50 bg-violet-500/10 shadow-[0_0_50px_rgba(124,58,237,0.18)]"}`} animate={{ scale: nodes.length ? [1, fractured ? 1.14 : 1.08, 1] : 1, rotate: fractured ? [0, 4, -4, 0] : 0 }} transition={{ duration: fractured ? 1.6 : 3, repeat: Infinity }} /><div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 text-center"><Network className={`mx-auto ${fractured ? "text-rose-500" : "text-violet-600"}`} /><p className={`mt-2 text-xs font-bold uppercase tracking-[0.2em] ${fractured ? "text-rose-600" : "text-violet-700"}`}>{nodes.length ? fractured ? "Conflict" : "AI Swarm" : "Awaiting Run"}</p></div>{nodes.map((node, index) => { const angle = (index / nodes.length) * Math.PI * 2; const x = 50 + Math.cos(angle) * 34; const y = 50 + Math.sin(angle) * 34; const approved = node.response === "APPROVE"; return <motion.div key={node.validator} className="absolute" style={{ left: `${x}%`, top: `${y}%` }} animate={{ y: node.disagrees ? [0, -12, 4, 0] : [0, -9, 0], opacity: [0.78, 1, 0.78] }} transition={{ duration: node.disagrees ? 1.5 : 2.4 + index * 0.2, repeat: Infinity }}><div className={`-translate-x-1/2 -translate-y-1/2 rounded-2xl border px-3 py-2 text-xs shadow-xl backdrop-blur ${node.disagrees ? "border-rose-300 bg-rose-50 text-rose-700" : approved ? "border-emerald-300 bg-emerald-50 text-emerald-700" : "border-violet-300 bg-violet-50 text-violet-700"}`}><div className="font-bold">{node.validator.replace(" Validator", "")}</div><div>{node.confidence}% · {node.response}</div></div></motion.div>; })}</div>;
});

export function GovernanceTimeline({ result }: { result: ConsensusResult | null }) {
  const steps = [["Proposal Submission", result?.proposal_id ?? "No proposal submitted"], ["Validator Review", `${result?.results.length ?? 0} AI validators coordinating`], ["Consensus Formation", result ? `${result.majority_decision} · ${result.weighted_consensus_score}% weighted` : "0% weighted consensus"], ["Risk Detection", result ? `${result.risk_level} · ${result.risk_analysis.overall_score}/100` : "0/100 risk score"], ["Governance Execution", result ? "Execution trace ready for Optimistic Democracy" : "No execution trail"]];
  return <section className="cs-panel rounded-3xl p-6"><h2 className="text-xl font-bold text-slate-950">Governance Timeline</h2><div className="mt-5 space-y-4">{steps.map(([title, detail], index) => <motion.div key={title} className="group flex gap-4 rounded-2xl p-2 transition hover:bg-violet-50" initial={{ opacity: 0, x: -12 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * 0.08 }}><div className="flex flex-col items-center"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-violet-100 text-violet-700 transition group-hover:scale-110 group-hover:bg-violet-200">{index + 1}</div>{index < steps.length - 1 ? <div className="h-8 w-px bg-slate-200" /> : null}</div><div><p className="font-semibold text-slate-950">{title}</p><p className="text-sm text-slate-500">{detail}</p></div></motion.div>)}</div></section>;
}

export function ConsensusHeatmap({ validators }: { validators: SimulationValidator[] }) {
  const proposals = ["GL-2041", "GL-2042", "GL-2043", "Live"];
  return <section className="cs-panel rounded-3xl p-6"><h2 className="text-xl font-bold text-slate-950">Disagreement Heatmap</h2><p className="mt-2 text-sm text-slate-500">Validators vs proposals, showing confidence clusters and dissent intensity.</p>{validators.length ? <div className="mt-5 overflow-x-auto"><div className="min-w-[520px] space-y-3"><div className="grid grid-cols-[120px_repeat(4,1fr)] gap-2 text-xs uppercase tracking-[0.16em] text-slate-500"><span />{proposals.map((proposal) => <span key={proposal}>{proposal}</span>)}</div>{validators.map((validator, rowIndex) => <div key={validator.validator} className="grid grid-cols-[120px_repeat(4,1fr)] gap-2"><span className="py-3 text-sm font-semibold text-slate-950">{validator.validator.replace(" Validator", "")}</span>{proposals.map((proposal, colIndex) => { const intensity = Math.max(12, Math.min(96, validator.disagrees ? validator.confidence : Math.abs(validator.confidence - colIndex * 9 - rowIndex * 5))); return <div key={proposal} className={`rounded-xl border p-3 text-center text-xs font-bold ${validator.disagrees ? "border-rose-300 bg-rose-50 text-rose-700" : "border-violet-200 bg-violet-50 text-violet-700"}`} style={{ opacity: 0.45 + intensity / 180 }}>{intensity}%</div>; })}</div>)}</div></div> : <EmptyState title="No heatmap yet" description="Run a governance simulation to reveal validator clusters and disagreement intensity." />}</section>;
}

export function MetricsGrid({ metrics }: { metrics: GovernanceMetrics | null }) {
  const cards = [["Average consensus", metrics?.average_confidence ?? 0, "%", CheckCircle2], ["Validator reliability", metrics ? Math.max(0, 100 - metrics.disagreement_rate) : 0, "%", Activity], ["Attack detection", metrics?.attack_likelihood_score ?? 0, "%", ShieldAlert], ["Governance throughput", metrics?.total_proposals ?? 0, " props", GitBranch]] as const;
  return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, suffix, Icon]) => <article key={label} className="cs-panel cs-panel-hover rounded-3xl p-5"><Icon className="text-violet-500" /><p className="mt-4 text-sm text-slate-500">{label}</p><p className="mt-1 text-3xl font-bold text-slate-950">{value}{suffix}</p></article>)}</div>;
}

export function RiskEngineCards({ riskAnalysis }: { riskAnalysis?: RiskAnalysis | null }) {
  const categories = riskAnalysis?.categories ?? {};
  const cards = [["Security risk", categories.security?.score ?? 0, "Prompt injection, exploit vectors, privilege escalation"], ["Governance risk", categories.governance?.score ?? 0, "Quorum capture, coordination bias, process integrity"], ["Economic risk", categories.economic?.score ?? 0, "Treasury impact, incentive drift, token pressure"], ["Consensus instability", categories.consensus?.score ?? 0, "Dissent density, confidence gaps, challenge likelihood"]] as const;
  return <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{cards.map(([label, score, description]) => { const tone = score >= 70 ? "border-rose-300 bg-rose-50 text-rose-700" : score >= 40 ? "border-amber-300 bg-amber-50 text-amber-700" : "border-emerald-300 bg-emerald-50 text-emerald-700"; return <article key={label} className={`cs-panel-hover rounded-3xl border p-5 ${tone}`}><div className="flex items-center justify-between"><p className="text-xs uppercase tracking-[0.18em] text-slate-500">{label}</p><Zap size={16} /></div><p className="mt-3 text-3xl font-black text-slate-950">{score}</p><div className="mt-3 h-2 rounded-full bg-white"><div className="h-2 rounded-full bg-current" style={{ width: `${Math.min(score, 100)}%` }} /></div><p className="mt-3 text-sm leading-6 text-slate-600">{description}</p></article>; })}</div>;
}

export function ProposalHistory({ proposals, onSelect }: { proposals: ProposalHistoryItem[]; onSelect?: (proposal: ProposalHistoryItem) => void }) {
  return <section className="cs-panel rounded-3xl p-6"><h2 className="text-xl font-bold text-slate-950">Proposal History</h2><div className="mt-5 space-y-3">{proposals.length ? proposals.map((proposal) => <button key={proposal.id} type="button" onClick={() => onSelect?.(proposal)} className="w-full rounded-2xl border border-slate-200 bg-white/80 p-4 text-left transition hover:-translate-y-0.5 hover:border-violet-300 hover:bg-violet-50"><div className="flex flex-wrap items-center justify-between gap-3"><p className="font-mono text-xs text-violet-600">{proposal.id}</p><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-800">{proposal.majority_decision}</span></div><p className="mt-2 line-clamp-2 text-sm text-slate-600">{proposal.prompt}</p><p className="mt-3 text-xs text-slate-500">{new Date(proposal.created_at).toLocaleString()} · {proposal.proposal_type} · risk {proposal.risk_score}/100 · weighted {proposal.weighted_consensus_score}%</p></button>) : <EmptyState title="No proposals stored" description="Start with a sample simulation to create proposal IDs, approval trails, and validator reasoning traces." />}</div></section>;
}

export function ActivityFeed({ events }: { events: GovernanceEvent[] }) {
  return <section className="cs-panel rounded-3xl p-6"><h2 className="text-xl font-bold text-slate-950">Real-Time Activity Feed</h2><div className="mt-5 space-y-3">{events.length ? events.map((event) => <div key={event.id} className="flex items-start gap-3 rounded-2xl border border-slate-200 bg-white/80 p-3 transition hover:border-emerald-300"><span className="mt-1 h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_18px_rgba(16,185,129,0.45)]" /><div><p className="text-sm font-semibold capitalize text-slate-950">{event.event_type.replaceAll("_", " ")}</p><p className="text-xs text-slate-500">{event.proposal_id} · {new Date(event.created_at).toLocaleTimeString()}</p></div></div>) : <EmptyState title="No activity yet" description="Validator decisions, risk alerts, approval trails, and lifecycle logs appear after simulations." />}</div></section>;
}
