import Link from "next/link";
import { BrainCircuit, Cpu, Database, GitBranch, Radar, ShieldCheck } from "lucide-react";

const sections = [
  ["Project overview", "ConsensusScope is a GenLayer-aligned Governance Intelligence Layer for Optimistic Democracy simulations, validator coordination, and risk-aware proposal execution."],
  ["Validator system", "Sentinel, Civic, Atlas, and Forge evaluate proposals through security, governance, economic, and technical lenses with confidence and memory state."],
  ["Consensus engine", "The engine combines majority decision, weighted confidence, disagreement rate, risk analysis, and validator reasoning traces into a protocol-grade verdict."],
  ["Prompt defense", "The prompt defense system detects injection patterns, governance manipulation, economic coercion, and consensus instability before execution."],
  ["API endpoints", "Core endpoints include /health, /simulate-consensus, /analyze-prompt, /governance/history, /governance/metrics, and /governance/events."],
  ["Milestones", "Project milestones track MVP proof, validator intelligence growth, submission readiness, and future GenLayer integration."],
  ["Future roadmap", "Roadmap items include live GenLayer handoff, richer validator reputation, challenge period simulation, and multi-proposal governance analytics."],
];

export default function DocsPage() {
  return <main className="cs-shell min-h-screen px-6 py-10 text-slate-950 lg:px-10"><div className="mx-auto max-w-7xl"><header className="rounded-[2rem] bg-black p-8 text-white"><Link href="/" className="text-sm font-bold text-violet-200">← ConsensusScope</Link><p className="mt-8 text-xs font-bold uppercase tracking-[0.22em] text-violet-200">Docs</p><h1 className="mt-3 max-w-4xl text-5xl font-black tracking-[-0.04em]">AI-native governance terminal for Optimistic Democracy.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">A cohesive operating surface for validator reasoning, weighted consensus, prompt defense, governance event intelligence, workflow tracing, and project milestones.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/workflow" className="rounded-full bg-violet-500 px-4 py-2 text-sm font-bold text-white">Open Workflow</Link><Link href="/milestones" className="rounded-full bg-white/10 px-4 py-2 text-sm font-bold text-white">View Milestones</Link><Link href="/dashboard" className="rounded-full bg-white px-4 py-2 text-sm font-bold text-slate-950">Launch Dashboard</Link></div></header><section className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{sections.map(([title, text], index) => { const icons = [BrainCircuit, ShieldCheck, GitBranch, Radar, Database, Cpu, GitBranch]; const Icon = icons[index]; return <article key={title} className="cs-panel cs-panel-hover rounded-3xl p-6"><Icon className="text-violet-500" /><h2 className="mt-5 text-xl font-bold">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-500">{text}</p></article>; })}</section><section className="cs-panel mt-8 rounded-3xl p-8"><h2 className="text-2xl font-black">Architecture Diagram</h2><div className="mt-6 grid gap-3 text-center text-sm font-bold md:grid-cols-6"><div className="rounded-2xl bg-slate-50 p-4">Proposal</div><div className="rounded-2xl bg-violet-50 p-4 text-violet-700">AI Validators</div><div className="rounded-2xl bg-indigo-50 p-4 text-indigo-700">Disagreement</div><div className="rounded-2xl bg-amber-50 p-4 text-amber-700">Risk Engine</div><div className="rounded-2xl bg-emerald-50 p-4 text-emerald-700">Consensus</div><div className="rounded-2xl bg-slate-950 p-4 text-white">Execution Trace</div></div></section></div></main>;
}
